# Grouped monthly update proposals (design §13). Every update still has to pass CI,
# including the cargo-deny license and build-script allow-lists.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    groups:
      docker:
        patterns: ["*"]
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    groups:
      cargo:
        patterns: ["*"]
